name       : python-sane
version    : 2.8.3
release    : 4
source     :
    - https://github.com/python-pillow/Sane/archive/v2.8.3.tar.gz : 1c3aa1c246007e9e6f7b11ca2c98256ebefed66f4ff13dcf38179c721677022f
license    : MIT
component  : programming.python
summary    : The SANE module provides an interface to the SANE scanner and frame grabber
    interface for Linux
description: |
    The SANE module provides an interface to the SANE scanner and frame grabber interface for Linux
builddeps  :
    - pkgconfig(python3)
    - pkgconfig(sane-backends)
build      : |
    %python3_setup
install    : |
    %python3_install
