name       : python-sane
version    : 2.8.2
release    : 1
source     :
    - https://pypi.python.org/packages/89/cf/a62e1416c18b0facc508c2ce4c0c77701154febc005ae8fdbfb65112755f/python-sane-2.8.2.tar.gz : 0f47e1c34ca94dcbe3136a05f05b342f055e6c129743f7f6e1a6519d6000316b
license    : MIT
component  : programming.python
summary    : The SANE module provides an interface to the SANE scanner and frame grabber interface for Linux
description: |
    The SANE module provides an interface to the SANE scanner and frame grabber interface for Linux
builddeps  :
    - pkgconfig(sane-backends)
build      : |
    %python_setup
install    : |
    %python_install
